### ISSUE TITLE
Project scope and install issues

### ISSUE THREAD

**Issue by mmontone** [tom95/sandblocks#30]
Hello.

This project looks very interesting. I wonder, is this a part of what is described in this thesis: ? 

https://shop.verlag.uni-potsdam.de/en/shop/sandblocks/

Also, I've tried running this in Squeak 5.3, but I get `#withScalingFactor` method not being defined.

**Comment by tom95** [comment]
Hi @mmontone ! I just pushed a fix for that error, an oversight when I loaded another project that defined this extension method.
In 5.3, you will likely not be able to load the full project as parts of the representation system depend on the new InspectorField classes in Squeak trunk. Copies of Squeak trunk VM/images can be found here if you want to try it out: http://files.squeak.org/trunk/

The TR you mentioned is in fact of another project. The name collision is very unfortunate and I'm planning to change the name of this repo's project as soon as possible. I ran short on time while finishing my master thesis on this project and did not get around to come up with a name in time for the submission.

My thesis itself is not published yet but some parts of the project are described in this workshop paper: https://dl.acm.org/doi/10.1145/3397537.3397560 Since the publication, a number of other interesting things happened that I'm planning to write down in a more succinct manner than in the thesis.

Hoping that the installation will work for you, I'll close this issue now :) If you have questions, either on this Sandblocks or the SandBlocks from the technical report you linked, please feel free to ask on this issue.
